# Generated by Django 5.2.6 on 2025-10-13 00:39

import applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(default=applications.models.generate_application_id, editable=False, max_length=20, unique=True)),
                ('clinic_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Klinika nomi')),
                ('complaint', models.TextField(blank=True, null=True, verbose_name='Shikoyatlar')),
                ('diagnosis', models.TextField(blank=True, null=True, verbose_name='Tashxis')),
                ('final_conclusion', models.TextField(blank=True, null=True, verbose_name='Yakuniy xulosa')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=20, verbose_name='Holat')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Arxivlanganmi')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Arxivlangan vaqt')),
            ],
            options={
                'verbose_name': 'Ariza',
                'verbose_name_plural': 'Arizalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Ariza Tarixi',
                'verbose_name_plural': 'Arizalar Tarixi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='application_documents/', verbose_name='Fayl')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fayl tavsifi')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqt')),
            ],
            options={
                'verbose_name': 'Ariza Hujjati',
                'verbose_name_plural': 'Ariza Hujjatlari',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
