# Generated by Django 5.2.5 on 2025-10-04 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at'], 'verbose_name': 'Murojaat', 'verbose_name_plural': 'Murojaatlar'},
        ),
        migrations.AlterModelOptions(
            name='applicationhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Murojaat Tarixi', 'verbose_name_plural': 'Murojaatlar Tarixi'},
        ),
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
        migrations.RemoveField(
            model_name='document',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='document',
            name='source_type',
        ),
        migrations.AddField(
            model_name='application',
            name='final_conclusion',
            field=models.TextField(blank=True, null=True, verbose_name='Yakuniy xulosa'),
        ),
        migrations.AlterField(
            model_name='application',
            name='clinic_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Klinika nomi'),
        ),
        migrations.AlterField(
            model_name='application',
            name='complaint',
            field=models.TextField(blank=True, null=True, verbose_name='Shikoyatlar'),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='document',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application', verbose_name='Murojaat'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='application_documents/', verbose_name='Fayl'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
