# Generated by Django 5.2.6 on 2025-10-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('in_progress', 'Jarayonda'), ('completed', 'Tugatilgan'), ('rejected', 'Rad etilgan')], default='new', max_length=20, verbose_name='Holat'),
        ),
    ]
