# Generated by Django 5.2.5 on 2025-10-02 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_linked_patient_applicationhistory'),
        ('patients', '0022_remove_patient_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='patients.stage', verbose_name='Bosqich'),
        ),
    ]
