# Generated by Django 5.2.5 on 2025-10-02 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_stage'),
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='stages.stage', verbose_name='Bosqich'),
        ),
    ]
