# Generated by Django 5.2.5 on 2025-10-02 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_application_stage'),
        ('patients', '0023_remove_patienthistory_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_documents', to='patients.patient', verbose_name='Bemor'),
        ),
        migrations.AddField(
            model_name='document',
            name='source_type',
            field=models.CharField(blank=True, choices=[('manual', 'Qo‘lda'), ('system', 'Tizim')], default='manual', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yuklagan foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='document',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application', verbose_name='Ariza'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Fayl'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yuklangan sana'),
        ),
    ]
