# Generated by Django 5.2.5 on 2025-12-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='code_name',
            field=models.CharField(default='default', max_length=30),
        ),
    ]
