# Generated by Django 5.2.7 on 2025-10-08 10:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_stage_options_alter_stage_code_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('color', models.CharField(default='default', max_length=32)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['order', 'id']},
        ),
        migrations.RemoveField(
            model_name='stage',
            name='name',
        ),
        migrations.AddField(
            model_name='stage',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stage',
            name='code_name',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='color',
            field=models.CharField(default='#999999', max_length=32),
        ),
    ]
