# Generated by Django 5.2.5 on 2025-10-26 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0003_patient_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Masalan: "Medion Klinika" yoki "Dr. Aliyev"', max_length=255, verbose_name='Klinika/Shifokor nomi')),
                ('code', models.CharField(help_text='Masalan: "MEDION_01"', max_length=50, unique=True, verbose_name='Hamkor kodi')),
                ('specialization', models.CharField(blank=True, help_text='Masalan: "Kardiologiya", "Nevrologiya"', max_length=255, null=True, verbose_name='Mutaxassislik')),
                ('contact_person', models.CharField(blank=True, help_text="Aloqa uchun mas'ul shaxs ismi", max_length=255, null=True, verbose_name="Mas'ul shaxs")),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telegram_chat_id', models.CharField(blank=True, help_text='Yangi bemorlar haqida xabarnoma uchun Telegram guruh ID', max_length=50, null=True, verbose_name='Telegram Chat ID')),
                ('is_active', models.BooleanField(default=True, help_text='Hamkor faolmi?', verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Hamkor',
                'verbose_name_plural': 'Hamkorlar',
                'db_table': 'partners_partner',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerResponseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Tibbiy xulosa, narxlar jadvali PDF/DOC', upload_to='partner_responses/%Y/%m/%d/', verbose_name='Fayl')),
                ('file_name', models.CharField(max_length=255, verbose_name='Fayl nomi')),
                ('title', models.CharField(blank=True, help_text='Masalan: "Tibbiy xulosa", "Narxlar jadvali"', max_length=255, null=True, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, help_text="Qo'shimcha ma'lumot", null=True, verbose_name='Izoh')),
                ('document_type', models.CharField(choices=[('medical_report', 'Tibbiy xulosa'), ('price_list', 'Narxlar jadvali'), ('recommendations', 'Tavsiyalar'), ('other', 'Boshqa')], default='medical_report', max_length=50, verbose_name='Hujjat turi')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqt')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_responses', to='partners.partner', verbose_name='Hamkor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_responses', to='patients.patient', verbose_name='Bemor')),
            ],
            options={
                'verbose_name': 'Hamkor javob xati',
                'verbose_name_plural': 'Hamkor javob xatlari',
                'db_table': 'partners_response_document',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
