# Generated by Django 5.2.5 on 2025-11-04 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerresponsedocument',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_responses', to='patients.patient', verbose_name='Bemor'),
        ),
    ]
