# Generated by Django 5.2.7 on 2025-11-26 01:22

import django.db.models.deletion
import partners.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='partner_avatars/', verbose_name='Profil rasmi'),
        ),
        migrations.CreateModel(
            name='OperatorPartnerConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Suhbat mavzusi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi xabar vaqti')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_op_partner_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
                ('operator', models.ForeignKey(limit_choices_to={'role': 'operator'}, on_delete=django.db.models.deletion.PROTECT, related_name='operator_partner_chats', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner_operator_chats', to='partners.partner', verbose_name='Partner')),
            ],
            options={
                'verbose_name': 'Operator-Partner Suhbat',
                'verbose_name_plural': 'Operator-Partner Suhbatlar',
                'db_table': 'partners_op_partner_conversation',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperatorPartnerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Matn'), ('file', 'Fayl'), ('system', 'Tizim xabari')], default='text', max_length=10, verbose_name='Xabar turi')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Xabar matni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='Tahrirlangan')),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilgan")),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='partners.operatorpartnerconversation', verbose_name='Suhbat')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='partners.operatorpartnermessage', verbose_name='Javob')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='op_partner_sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Yuboruvchi')),
            ],
            options={
                'verbose_name': 'Operator-Partner Xabar',
                'verbose_name_plural': 'Operator-Partner Xabarlar',
                'db_table': 'partners_op_partner_message',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OperatorPartnerAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=partners.models.op_partner_chat_upload_path, verbose_name='Fayl')),
                ('file_type', models.CharField(choices=[('image', 'Rasm'), ('video', 'Video'), ('document', 'Hujjat'), ('other', 'Boshqa')], default='other', max_length=20, verbose_name='Fayl turi')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME turi')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='Hajm (bytes)')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Asl fayl nomi')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqt')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='op_partner_chat_files', to=settings.AUTH_USER_MODEL, verbose_name='Yuklagan')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='partners.operatorpartnermessage', verbose_name='Xabar')),
            ],
            options={
                'verbose_name': 'Operator-Partner Fayl',
                'verbose_name_plural': 'Operator-Partner Fayllar',
                'db_table': 'partners_op_partner_attachment',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='operatorpartnerconversation',
            index=models.Index(fields=['operator', 'is_active'], name='partners_op_operato_398fb1_idx'),
        ),
        migrations.AddIndex(
            model_name='operatorpartnerconversation',
            index=models.Index(fields=['partner', 'is_active'], name='partners_op_partner_dbbf0c_idx'),
        ),
        migrations.AddIndex(
            model_name='operatorpartnerconversation',
            index=models.Index(fields=['last_message_at'], name='partners_op_last_me_8032b8_idx'),
        ),
        migrations.AddConstraint(
            model_name='operatorpartnerconversation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('operator', 'partner'), name='unique_active_op_partner_conversation'),
        ),
        migrations.AddIndex(
            model_name='operatorpartnermessage',
            index=models.Index(fields=['conversation', 'created_at'], name='partners_op_convers_0f82db_idx'),
        ),
        migrations.AddIndex(
            model_name='operatorpartnermessage',
            index=models.Index(fields=['sender', 'created_at'], name='partners_op_sender__fcf429_idx'),
        ),
        migrations.AddIndex(
            model_name='operatorpartnermessage',
            index=models.Index(fields=['conversation', 'is_read'], name='partners_op_convers_46bf2a_idx'),
        ),
        migrations.AddIndex(
            model_name='operatorpartnerattachment',
            index=models.Index(fields=['message', 'uploaded_at'], name='partners_op_message_ecafc2_idx'),
        ),
        migrations.AddIndex(
            model_name='operatorpartnerattachment',
            index=models.Index(fields=['uploaded_by'], name='partners_op_uploade_557638_idx'),
        ),
    ]
