# Generated by Django 5.2.7 on 2025-12-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tag_code_name'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='core.tag'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='hotels', to='core.tag'),
        ),
        migrations.AddField(
            model_name='simcardrequest',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='simcard_requests', to='core.tag'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='transfer_requests', to='core.tag'),
        ),
        migrations.AddField(
            model_name='translatorrequest',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='translator_requests', to='core.tag'),
        ),
        migrations.AddField(
            model_name='visarequest',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='visa_requests', to='core.tag'),
        ),
    ]
