# Generated by Django 5.2.7 on 2025-11-11 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
        ('patients', '0002_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='patients.patient'),
        ),
    ]
