# Generated by Django 5.2.5 on 2025-09-05 11:36

import consultations.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(blank=True, help_text="Masalan: O'RVI, astenik sindrom")),
                ('recommendations', models.TextField(blank=True, help_text='Har satrda bitta tavsiya. UI ro‘yxatga ajratadi.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('instruction', models.TextField(blank=True)),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['-id']},
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=consultations.models.chat_upload_path),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['message', '-id'], name='consultatio_message_7d3a07_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'id'], name='consultatio_convers_d89e54_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'id'], name='consultatio_sender__4ccf5f_idx'),
        ),
        migrations.AddIndex(
            model_name='readreceipt',
            index=models.Index(fields=['user', 'message'], name='consultatio_user_id_796b79_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('patient', 'doctor'), name='uniq_patient_doctor_conversation'),
        ),
        migrations.AddField(
            model_name='doctorsummary',
            name='conversation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='consultations.conversation'),
        ),
        migrations.AddField(
            model_name='doctorsummary',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescription',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='consultations.conversation'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions_authored', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['conversation', '-id'], name='consultatio_convers_e13ae1_idx'),
        ),
    ]
