# Generated by Django 5.2.5 on 2025-09-21 17:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_messages', models.PositiveIntegerField(default=0)),
                ('total_files', models.PositiveIntegerField(default=0)),
                ('first_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctorsummary',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='doctorsummary',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='created_by',
        ),
        migrations.AlterUniqueTogether(
            name='readreceipt',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='readreceipt',
            name='message',
        ),
        migrations.RemoveField(
            model_name='readreceipt',
            name='user',
        ),
        migrations.RemoveConstraint(
            model_name='conversation',
            name='uniq_patient_doctor_conversation',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='consultatio_sender__4ccf5f_idx',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='doctor',
        ),
        migrations.AddField(
            model_name='attachment',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='conversation',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operator_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='is_read_by_recipient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('operator', 'Operator')], max_length=16),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['message', 'uploaded_at'], name='consultatio_message_534651_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['uploaded_by'], name='consultatio_uploade_37cd8d_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['patient', 'is_active'], name='consultatio_patient_f2cb1c_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['operator', 'is_active'], name='consultatio_operato_bafd0b_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['last_message_at'], name='consultatio_last_me_9fb918_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='consultatio_convers_49290b_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='consultatio_sender__92cf91_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['reply_to'], name='consultatio_reply_t_0b8418_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['conversation', 'role'], name='consultatio_convers_9e7b73_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['user', 'is_muted'], name='consultatio_user_id_c9964f_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('patient', 'operator'), name='uniq_patient_operator_conversation'),
        ),
        migrations.AddField(
            model_name='conversationstats',
            name='conversation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='consultations.conversation'),
        ),
        migrations.AddField(
            model_name='messagereadstatus',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='consultations.message'),
        ),
        migrations.AddField(
            model_name='messagereadstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_read_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DoctorSummary',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
        migrations.DeleteModel(
            name='ReadReceipt',
        ),
        migrations.AddIndex(
            model_name='messagereadstatus',
            index=models.Index(fields=['message', 'user'], name='consultatio_message_6eb175_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereadstatus',
            index=models.Index(fields=['user', 'read_at'], name='consultatio_user_id_a6ccc8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagereadstatus',
            unique_together={('message', 'user')},
        ),
    ]
