# Generated by Django 5.2.5 on 2025-09-05 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_doctorsummary_prescription_alter_attachment_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attachment',
            name='consultatio_message_7d3a07_idx',
        ),
    ]
