# Generated by Django 5.2.5 on 2025-09-27 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_doctorsummary_operator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='conversation',
        ),
        migrations.DeleteModel(
            name='DoctorSummary',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
