# Generated by Django 5.2.7 on 2025-11-04 17:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100)),
                ('name_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Blog toifasi',
                'verbose_name_plural': 'Blog toifalari',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=255)),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Qisqa tavsif (UZ)')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Qisqa tavsif (RU)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Qisqa tavsif (EN)')),
                ('content_uz', models.TextField(verbose_name='To‘liq matn (UZ)')),
                ('content_ru', models.TextField(blank=True, null=True, verbose_name='To‘liq matn (RU)')),
                ('content_en', models.TextField(blank=True, null=True, verbose_name='To‘liq matn (EN)')),
                ('author', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='blog/images/')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='review.blogcategory')),
            ],
            options={
                'verbose_name': 'Blog maqola',
                'verbose_name_plural': 'Blog maqolalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Sharh matni')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Tasdiqlanganmi')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Sharh',
                'verbose_name_plural': 'Sharhlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
