# Generated by Django 5.2.7 on 2025-11-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_operatorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='operator_avatars/', verbose_name='Profil rasmi'),
        ),
    ]
