# Generated by Django 5.2.5 on 2025-10-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Bosqich nomi')),
                ('color', models.CharField(default='primary', help_text='Masalan: primary, success, danger yoki #FF5733', max_length=20, verbose_name='Rang')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Tartib raqami')),
                ('code_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kod nomi (dasturchi uchun)')),
            ],
            options={
                'verbose_name': 'Bosqich',
                'verbose_name_plural': 'Bosqichlar',
                'ordering': ['order'],
            },
        ),
    ]
