# Generated by Django 5.2.5 on 2025-10-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='stage',
            name='code_name',
            field=models.CharField(default='default_code', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='color',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
