# Generated by Django 5.2.5 on 2025-10-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='code_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Kod nomi (dasturchi uchun)'),
        ),
    ]
