# Generated by Django 5.2.5 on 2025-10-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0002_stage_code_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='code_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kod nomi (dasturchi uchun)'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Bosqich nomi'),
        ),
    ]
