# Generated by Django 5.2.4 on 2025-07-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='departments',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='departments',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='departments',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='departments',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='departments',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
