# Generated by Django 5.2.5 on 2025-09-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='complaints',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='passport',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='previous_diagnosis',
            field=models.TextField(blank=True, default=''),
        ),
    ]
