# Generated by Django 5.2.7 on 2025-10-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='source',
        ),
        migrations.AddField(
            model_name='patient',
            name='passport',
            field=models.CharField(blank=True, default=None, max_length=9, null=True),
        ),
    ]
