# Generated by Django 5.2.6 on 2025-10-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_patient_source_patient_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Profil rasmi'),
        ),
    ]
