# Generated by Django 5.2.5 on 2025-09-19 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patientprofile_complaints_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientdocument',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Hujjat', 'verbose_name_plural': 'Hujjatlar'},
        ),
        migrations.AlterModelOptions(
            name='patienthistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tarix', 'verbose_name_plural': 'Tarixlar'},
        ),
    ]
