# Generated by Django 5.2.5 on 2025-09-19 18:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patientdocument_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientprofile',
            options={'verbose_name': 'Bemor Profili', 'verbose_name_plural': 'Bemor Profillari'},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['order'], 'verbose_name': 'Bosqich', 'verbose_name_plural': 'Bosqichlar'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Teg', 'verbose_name_plural': 'Teglar'},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patients', to=settings.AUTH_USER_MODEL, verbose_name='Kim yaratdi'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name="To'liq ism"),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Telefon +998XXXXXXXXX ko‘rinishida bo‘lsin', regex='^\\+998\\d{9}$')], verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='source',
            field=models.CharField(blank=True, max_length=50, verbose_name='Manba'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='patients.stage', verbose_name='Bosqich'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='patients.tag', verbose_name='Teg'),
        ),
        migrations.AlterField(
            model_name='patientdocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='complaints',
            field=models.TextField(blank=True, default='', verbose_name='Shikoyatlar'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana"),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10, null=True, verbose_name='Jinsi'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='previous_diagnosis',
            field=models.TextField(blank=True, default='', verbose_name='Avvalgi diagnozlar'),
        ),
    ]
