# Generated by Django 5.2.5 on 2025-10-26 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
        ('patients', '0003_patient_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bemor', 'verbose_name_plural': 'Bemorlar'},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='passport',
        ),
        migrations.AddField(
            model_name='patient',
            name='assigned_partner',
            field=models.ForeignKey(blank=True, help_text='Operator tomonidan tanlanadi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_patients', to='partners.partner', verbose_name='Biriktirilgan hamkor'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Bemor qachon yaratilgan', verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Oxirgi yangilanish vaqti', verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterModelTable(
            name='patient',
            table='patients_patient',
        ),
    ]
