# Generated by Django 5.2.5 on 2025-09-19 19:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patientprofile_options_alter_stage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patienthistory',
            options={},
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Telefon +998XXXXXXXXX ko‘rinishida bo‘lsin', regex='^\\+998\\d{9}$')]),
        ),
    ]
