# Generated by Django 5.2.5 on 2025-09-19 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_patientprofile_full_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patienthistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tarix', 'verbose_name_plural': 'Tarixlar'},
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='patientdocument',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='patientdocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
