# Generated by Django 5.2.5 on 2025-09-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_alter_patienthistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
