# Generated by Django 5.2.5 on 2025-09-20 11:33

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_patientprofile_full_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientprofile',
            options={'verbose_name': 'Bemor Profili', 'verbose_name_plural': 'Bemor Profillari'},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['order'], 'verbose_name': 'Bosqich', 'verbose_name_plural': 'Bosqichlar'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Teglar'},
        ),
        migrations.AddField(
            model_name='patient',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], default='Erkak', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='passport',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=20, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='source',
            field=models.CharField(blank=True, default='Anketa', max_length=50),
        ),
        migrations.AlterField(
            model_name='patientdocument',
            name='source_type',
            field=models.CharField(choices=[('operator', 'Operator'), ('patient', 'Bemor'), ('partner', 'Hamkor')], default='operator', max_length=20),
        ),
    ]
