# Generated by Django 5.2.5 on 2025-09-20 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_alter_patientprofile_options_alter_stage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientprofile',
            options={'verbose_name': 'Bemor Profili'},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='passport',
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Telefon +998XXXXXXXXX ko‘rinishida bo‘lsin', regex='^\\+998\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='source',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='patientdocument',
            name='source_type',
            field=models.CharField(choices=[('operator', 'Operator'), ('patient', 'Bemor'), ('partner', 'Hamkor')], max_length=20),
        ),
    ]
