# Generated by Django 5.2.5 on 2025-09-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_alter_patientprofile_options_alter_stage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
