# Generated by Django 5.2.5 on 2025-10-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_alter_patient_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
