# Generated by Django 5.2.5 on 2025-10-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0018_applicationstatus_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='tag',
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={},
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='code_name',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='order',
        ),
        migrations.AddField(
            model_name='patient',
            name='stageId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
