# Generated by Django 5.2.5 on 2025-10-02 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0019_remove_patient_tag_alter_stage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='patients.application')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ariza Tarixi',
                'verbose_name_plural': 'Ariza Tarixlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PatientHistory',
        ),
    ]
