# Generated by Django 5.2.5 on 2025-10-02 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0021_tag_remove_application_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='stage',
        ),
    ]
