# Generated by Django 5.2.5 on 2025-10-02 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0022_remove_patient_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patienthistory',
            name='author',
        ),
        migrations.RemoveField(
            model_name='patienthistory',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Stage',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='tag',
        ),
        migrations.DeleteModel(
            name='PatientHistory',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
